// Objective-C API for talking to github.com/keybase/go-keychain/bind Go package.
//   gobind -lang=objc github.com/keybase/go-keychain/bind
//
// File is generated by gobind. Do not edit.

#ifndef __Bind_H__
#define __Bind_H__

@import Foundation;
#include "Universe.objc.h"


@protocol BindTest;
@class BindTest;

@protocol BindTest <NSObject>
- (void)fail:(NSString*)s;
@end

/**
 * AddGenericPassword adds generic password
 */
FOUNDATION_EXPORT BOOL BindAddGenericPassword(NSString* service, NSString* account, NSString* label, NSString* password, NSString* accessGroup, NSError** error);

/**
 * DeleteGenericPassword deletes generic password
 */
FOUNDATION_EXPORT BOOL BindDeleteGenericPassword(NSString* service, NSString* account, NSString* accessGroup, NSError** error);

/**
 * GenericPasswordTest runs test code for generic password keychain item.
This is here so we can export using gomobile bind and run this method on iOS simulator and device.
Access groups aren't supported in iOS simulator.
 */
FOUNDATION_EXPORT void BindGenericPasswordTest(id<BindTest> t, NSString* service, NSString* accessGroup);

@class BindTest;

/**
 * Test is a bind interface for the test
 */
@interface BindTest : NSObject <goSeqRefInterface, BindTest> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)fail:(NSString*)s;
@end

#endif
