// Objective-C API for talking to github.com/keybase/go-keychain/bind Go package.
//   gobind -lang=objc github.com/keybase/go-keychain/bind
//
// File is generated by gobind. Do not edit.

#ifndef __GoBind_H__
#define __GoBind_H__

#include <Foundation/Foundation.h>

@protocol GoBindTest
- (void)Fail:(NSString*)s;
@end

FOUNDATION_EXPORT BOOL GoBindAddGenericPassword(NSString* service, NSString* account, NSString* label, NSString* password, NSString* accessGroup, NSError** error);

FOUNDATION_EXPORT BOOL GoBindDeleteGenericPassword(NSString* service, NSString* account, NSString* accessGroup, NSError** error);

FOUNDATION_EXPORT void GoBindGenericPasswordTest(id<GoBindTest> t, NSString* service, NSString* accessGroup);

#endif
