// Objective-C API for talking to github.com/keybase/go-keychain/bind Go package.
//   gobind -lang=objc github.com/keybase/go-keychain/bind
//
// File is generated by gobind. Do not edit.

#ifndef __GoBind_H__
#define __GoBind_H__

#include <Foundation/Foundation.h>

FOUNDATION_EXPORT BOOL GoBindAddGenericPassword(NSString* service, NSString* account, NSString* label, NSString* accessGroup, NSString* password, NSError** error);

FOUNDATION_EXPORT BOOL GoBindDeleteGenericPassword(NSString* service, NSString* account, NSString* label, NSString* accessGroup, NSError** error);

FOUNDATION_EXPORT BOOL GoBindTestGenericPassword(NSString* service, NSString* accessGroup, NSError** error);

#endif
